server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/adminumb/task-config-repo.git
          default-label: main  # Это ветка, которую использовать, по умолчанию - main
  application:
    name: config-server
